name: strawberry-kyu
base: core24
adopt-info: strawberry-app
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: A music player and collection organizer
description: |
  Strawberry is a music player and music collection organizer. It is aimed at music collectors and audiophiles.
  Strawberry is free software released under GPL. It's written in C++ using the Qt framework and GStreamer. 
grade: stable
confinement: strict
icon: strawberry.png

apps:
  strawberry-kyu:
    command: usr/bin/strawberry
    desktop: usr/share/applications/org.strawberrymusicplayer.strawberry.desktop
    common-id: org.strawberrymusicplayer.strawberry
    environment:
      QT_QPA_PLATFORMTHEME: xdgdesktopportal
      LD_LIBRARY_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      QT_PLUGIN_PATH: $SNAP/lxqt-support-core24/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins:$QT_PLUGIN_PATH
    extensions: [kde-neon-6]
    plugs:
      - home
      - removable-media
      - mount-observe
    slots:
      - mpris

plugs:
  lxqt-support-core24:
    content: lxqt-support-core24
    interface: content
    target: $SNAP/lxqt-support-core24
    default-provider: lxqt-support-core24

layout:
  /usr/share/color-schemes:
    symlink: $SNAP/lxqt-support-core24/usr/share/color-schemes
  /usr/share/Kvantum:
    symlink: $SNAP/lxqt-support-core24/usr/share/Kvantum

package-repositories:
  - type: apt
    url: https://ppa.launchpadcontent.net/jonaski/strawberry/ubuntu
    suites: [noble]
    components: [main]
    architectures: [arm64, amd64]
    key-id: BE5ED0F9261CAAD9A1E5B1A4CD6289E999EA819D

parts:
  strawberry-app:
    plugin: nil
    stage-packages:
      - strawberry
    override-stage: |
      craftctl default
      sed -i 's|Name=Strawberry|Name=Strawberry [Kyu]|' $CRAFT_STAGE/usr/share/applications/org.strawberrymusicplayer.strawberry.desktop
      craftctl set version=$(dpkg-parsechangelog -l $CRAFT_PART_INSTALL/usr/share/doc/strawberry/changelog.*.gz -S Version | sed -e s/1://g)
    prime:
      - usr/bin/strawberry
      - usr/share/applications/org.strawberrymusicplayer.strawberry.desktop
      - usr/share/icons/hicolor/*/apps/strawberry.png

  dependencies:
    after: [strawberry-app]
    plugin: nil
    stage-packages:
      - libcdio19t64
      - libebur128-1
      - libfftw3-double3
      - libkdsingleapplication-qt6-1.0
      - libgpod4t64
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcdio.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libebur128.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfftw3.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfftw3_omp.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfftw3_threads.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgpod.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkdsingleapplication-qt6.so*
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gstreamer-1.0
      - usr/share/gstreamer-1.0
      - usr/share/locale
